// Decompile every function in the current program to a single C file.
// Usage: -postScript DecompileAll.java <outFileBasename>
// Output: /workspace/re-workspace/exports/<basename>.c
//@category IceCam

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import java.io.File;
import java.io.FileWriter;

public class DecompileAll extends GhidraScript {

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        String base = args.length > 0 ? args[0] : currentProgram.getName();
        File outDir = new File("/workspace/re-workspace/exports");
        outDir.mkdirs();
        File out = new File(outDir, base + ".c");

        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);

        int ok = 0, fail = 0;
        try (FileWriter w = new FileWriter(out)) {
            w.write("// Full decompilation of " + currentProgram.getName()
                    + " (imageBase=" + currentProgram.getImageBase() + ")\n");
            w.write("// Generated by Ghidra headless DecompileAll.java\n\n");
            FunctionIterator it = currentProgram.getFunctionManager().getFunctions(true);
            while (it.hasNext() && !monitor.isCancelled()) {
                Function fn = it.next();
                if (fn.isThunk()) continue;
                DecompileResults res = decomp.decompileFunction(fn, 90, monitor);
                w.write("// ===== " + fn.getName() + " @ " + fn.getEntryPoint()
                        + " size=" + fn.getBody().getNumAddresses() + " =====\n");
                if (res != null && res.decompileCompleted()) {
                    w.write(res.getDecompiledFunction().getC());
                    ok++;
                } else {
                    String err = (res == null) ? "null" : res.getErrorMessage();
                    w.write("// [decompile failed: " + err + "]\n");
                    fail++;
                }
                w.write("\n");
            }
        }
        println("DecompileAll wrote " + out.getAbsolutePath() + " ok=" + ok + " fail=" + fail);
    }
}
